core/urls.py
# This file is part of ZUKS-Website.
#
# ZUKS-Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ZUKS-Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ZUKS-Website. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from core import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),

	url(r'^impressum/$', views.static, {'site' : 'impressum.html'}, name='impressum'),
	url(r'^presse/$', RedirectView.as_view(url='https://zuks.totemapp.com/', permanent=True), name='presse'),
	url(r'^konzept/$', views.static, {'site' : 'konzept.html'}, name='konzept'),

	url(r'^send_contactmail/$', views.send_contactmail, name='send_contactmail'),

	url(r'^subscribe/$', views.subscribeToNewsletter, name='subscribe'),
	url(r'^confirm/(?P<id>.+)/$', views.confirmNewsletter, name='confirm'),
	url(r'^unsubscribe/(?P<id>.+)/$', views.unsubscribeFromNewsletter, name='unsubscribe'),
	url(r'^news/(?P<newsId>[0-9]+)/(?P<user>.+)?$', views.viewNewsletter, name='newsletter'),

	url(r'^robots\.txt/$', views.static, {'site' : 'robots.txt', 'content_type' : 'text/plain'}, name='robots'),
	url(r'^sitemap\.xml/$', views.static, {'site' : 'sitemap.xml', 'content_type' : 'text/xml'}, name='sitemap'),
	url(r'^google2ba41cbba49d5958\.html/$', views.static, {'site' : 'google2ba41cbba49d5958.html'}, name='google_verification'),
)

zuks/urls.py
# This file is part of ZUKS-Website.
#
# ZUKS-Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ZUKS-Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ZUKS-Website. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'zuks.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls')),
)

core/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# This file is part of ZUKS-Website.
#
# ZUKS-Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ZUKS-Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ZUKS-Website. If not, see <http://www.gnu.org/licenses/>.

from django.db import models
from datetime import datetime
from django.conf import settings
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from core import mail
import pytz
import hashlib


class NewsletterRecipient(models.Model):
	class Meta:
		verbose_name = _("Newsletter Recipient")
		verbose_name_plural = _("Newsletter Recipients")

	email = models.EmailField(unique=True, verbose_name=_("Email address"))
	confirm_id = models.CharField(max_length=40, unique=True, verbose_name=_("Confirmation identifier"), help_text=_("Id the recipient could use to confirm his Email address and unregister the newsletter"))
	register_date = models.DateTimeField(auto_now_add=True, verbose_name=_("Registration date"))
	confirmed = models.BooleanField(default=False, verbose_name=_("Confirmation status"))
	confirm_date = models.DateTimeField(null=True, blank=True, verbose_name=_("Confirmation date"))

	def confirm(self):
		self.confirmed = True
		# as we work with the local times, we have to set it with the correct timezone.
		self.confirm_date = datetime.now().replace(tzinfo=pytz.timezone(settings.TIME_ZONE)) if settings.USE_TZ else datetime.now()

	def save(self, *args, **kwargs):
		src = (self.email + datetime.now().isoformat()).encode('utf-8')
		self.confirm_id = hashlib.sha1(src).hexdigest()

		super(NewsletterRecipient, self).save(*args, **kwargs)


	def __unicode__(self):
		return self.email;

class Newsletter(models.Model):
	class Meta:
		verbose_name = _("Newsletter")
		verbose_name_plural = _("Newsletters")

	sender = "info@zuks.org"

	content = models.TextField(verbose_name=_("Content"))
	subject = models.CharField(max_length=100, verbose_name=_("Subject"))
	send_date = models.DateTimeField(auto_now_add=True, verbose_name=_("Send date"))

	def __unicode__(self):
		return self.subject

	def save(self, *args, **kwargs):
		super(Newsletter, self).save(*args, **kwargs)

		# Send mails
		recipients = NewsletterRecipient.objects.filter(confirmed=True)
		mail.sendMail(self.sender, recipients, self.content, self.id, self.subject, skip_errors=True)

class ContactMail(models.Model):
	class Meta:
		verbose_name = _("Contact Mail")
		verbose_name_plural = _("Contact Mails")

	recipient = "info@zuks.org"
	subject = _("ZUKS Contact request")
	text_pattern = _("Sender: %(sender)s\nDate: %(date)s\nSubject: %(subject)s\n\n%(content)s")

	name = models.CharField(max_length=100, verbose_name=_("Name"))
	sender = models.EmailField(max_length=128, verbose_name=_("Email address"))
	contact_date = models.DateTimeField(auto_now_add=True, verbose_name=_("Date"))
	sendersubject = models.CharField(max_length=100, verbose_name=_("Subject"))
	content = models.TextField(verbose_name=_("Text"))

	def __unicode__(self):
		return self.subject

	def save(self, *args, **kwargs):
		super(ContactMail, self).save(*args, **kwargs)

		# Send mail
		text = self.text_pattern % {
			'sender' : self.sender,
			'date' 	: str(self.contact_date),
			'subject' : self.sendersubject,
			'content' : self.content
		}
		send_mail(self.subject, text, self.sender, [self.recipient])

core/forms.py
# This file is part of ZUKS-Website.
#
# ZUKS-Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ZUKS-Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ZUKS-Website. If not, see <http://www.gnu.org/licenses/>.

from django import forms
from core.models import ContactMail, Newsletter

class ContactForm(forms.ModelForm):
	class Meta:
		model = ContactMail
		fields = ['name', 'sender', 'sendersubject', 'content']

class NewsletterForm(forms.ModelForm):
	class Meta:
		model = Newsletter
		fields = ['subject', 'content']

core/views.py
# -*- coding: utf-8 -*-
# This file is part of ZUKS-Website.
#
# ZUKS-Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ZUKS-Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ZUKS-Website. If not, see <http://www.gnu.org/licenses/>.

from django.shortcuts import render
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.template.loader import render_to_string
from django.core.validators import EmailValidator
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.http import Http404, HttpResponse
from django.utils.translation import ugettext as _
from django.core.mail import send_mail
from django.utils.html import escape
from django.utils.safestring import mark_safe
from markdown import Markdown
from core.forms import ContactForm
from core import mail
from core.models import NewsletterRecipient, Newsletter
import logging

def index(request):
	form = ContactForm()
	context = RequestContext(request)
	context_dic = {"form": form}

	return render_to_response('core/index.html', context_dic, context)

def static(request, site, content_type="text/html"):
	return render_to_response(
		'core/{0}'.format(site),
		{},
		RequestContext(request),
		content_type=content_type
	)

def send_contactmail(request):
	'''
	Called via ajax.
	'''
	context = RequestContext(request)
	status = False

	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()
			status = True
	else:
		form = ContactForm()

	return render_to_response('core/contact_form.html', {
			'form': form,
			'success': status
		}, context)

def subscribeToNewsletter(request):
	'''
	Called via ajax.
	'''
	context = RequestContext(request)
	context_dic = {}

	if request.method == 'POST':
		try:
			email = request.POST['email'] if 'email' in request.POST else ''

			validator = EmailValidator(message=_('Please enter a valid email address'))
			validator(email)

			recp = NewsletterRecipient(email=email)
			recp.save()

			text = render_to_string('core/mail/subscribe.md', {'subscribe_id' : recp.confirm_id}, context)
			mail.sendMail('info@zuks.org', [recp], text, None, _('ZUKS Newsletter Registration'),  display_unsubscribe=False)

			context_dic['success'] = True
		except ValidationError as e:
			context_dic['error'] = e.message
		except IntegrityError:
			context_dic['error'] = _("For this mail a newsletter is already requested.")
		except:
			logging.exception("Newsletter subscribtion failed")
			context_dic['error'] = _("Unfortunately, the request could not be processed. Please try again later.")

			try:
				# Cleanup mail adress from database
				recp.delete()
			except:
				pass

	return render_to_response('core/subscribe_form.html', context_dic, context)

def confirmNewsletter(request, id):
	context = RequestContext(request)
	status = 'success'

	try:
		recp = NewsletterRecipient.objects.get(confirm_id=id)
		recp.confirm()
		recp.save()
	except NewsletterRecipient.DoesNotExist:
		status = 'expired'

	return render_to_response('core/confirm.html', {'status' : status}, context)

def unsubscribeFromNewsletter(request, id):
	context = RequestContext(request)

	try:
		recp = NewsletterRecipient.objects.get(confirm_id=id)
		recp.delete()
	except NewsletterRecipient.DoesNotExist:
		# Is already unsubscribed, nothing to do
		pass

	return render_to_response('core/unsubscribe.html', {}, context)

def viewNewsletter(request, newsId, user = None):
	context = RequestContext(request)

	try:
		news = Newsletter.objects.get(id=newsId)
	except Newsletter.DoesNotExist:
		raise Http404(_('Newsletter could not be found.'))

	if user is not None:
		usr = NewsletterRecipient.objects.get(confirm_id=user)
	else:
		usr = None

	unsubscribeId = usr.confirm_id if usr is not None else None
	mailContent = mark_safe(Markdown().convert(escape(news.content)))
	(txt, mailContent) = mail.renderContent(news.content, newsId, unsubscribeId, tpl='core/mail/news_body.html')
	# remove <html>/<body>/<head> data.
	mailContent = mailContent.replace('<html>', '').replace('</html>', '').replace('<head></head>', '').replace('</body>', '')
	mailContent = mailContent[mailContent.index('>', mailContent.index('<body'))+1:]

	return render_to_response(
		'core/newsletter.html', {
			'news': news,
			'newsContent': mailContent,
			'newsId': newsId,
			'userId': user,
		}, context
	)

templates/core/base.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="ZUKS">

    {% block "metadata" %}
    {% endblock "metadata" %}

    <title>ZUKS - {% trans "Civilian Support in Civil Protection" %}</title>
    <link rel="shortcut icon" href="{% static "img/favicon.png" %}?v=2" type="image/x-icon" />
    <!-- Stylesheets -->
    <link type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <link type="text/css" href='https://fonts.googleapis.com/css?family=Roboto:400,400italic,700,700italic,500italic,500,300italic,300' rel='stylesheet' >
    <link type="text/css" href="{% static "css/rondo/style.css" %}" rel="stylesheet">
    <link type="text/css" href="{% static "css/style.css" %}" rel="stylesheet">
</head>

<body>
    <header class="header" id="jump">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                        <span class="sr-only">{% trans "Toggle navigation" %}</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span><span class="icon-bar"></span>
                    </button>
                    {% block "logo" %}
                        <a class="navbar-brand" href="{% url "index" %}#"><img src="{% static "img/logo/logo@300.png" %}" alt="ZUKS Logo" /></a>
                    {% endblock "logo" %}
                </div>
                <div class="collapse navbar-collapse hidden-xs" id="default-menu">
                    <ul class="nav navbar-nav navbar-right">
                        {% block "menu" %}
                        {% endblock "menu" %}
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
                <div class="collapse navbar-responsive-collapse" id="mobile-menu">
                    <ul class="nav navbar-nav">
                        {% block "mobile_menu" %}
                        {% endblock "mobile_menu" %}
                    </ul>
                </div>
                <!-- /.navbar-responsive-collapse -->
            </div>
        </nav>
    </header>

    {% block "content" %}
    {% endblock "content" %}


    <!--Scripts-->
    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static "js/jquery.smooth-scroll.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.form.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.easing.1.3.js" %}" ></script>
    <script type="text/javascript" src="{% static "js/modernizr.js" %}"></script>
    <script type="text/javascript" src="{% static "js/custom.js" %}"></script>

    {% block "scripts" %}
    {% endblock "scripts" %}

    {% if settings.PIWIK_URL %}
        <!-- Piwik -->
        <script type="text/javascript">
          var _paq = _paq || [];
          _paq.push(["setDoNotTrack", true]);
          _paq.push(['trackPageView']);
          _paq.push(['enableLinkTracking']);
          (function() {
            var u="{{ settings.PIWIK_URL }}";
            _paq.push(['setTrackerUrl', u+'piwik.php']);
            _paq.push(['setSiteId', {{ settings.PIWIK_SITE_ID }}]);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript';
            g.defer=true; g.async=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
          })();
        </script>
        <noscript><p><img src="{{ settings.PIWIK_URL }}piwik.php?idsite={{ settings.PIWIK_SITE_ID }}" style="border:0;" alt="" /></p></noscript>
        <!-- End Piwik Code -->
    {% endif %}
</body>
</html>

templates/core/confirm.html
{% extends "core/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block "metadata" %}
    <meta name="description" content="{% trans "Newsletter registration" %}">
{% endblock "metadata" %}

{% block "menu" %}
  <li><a href="{% url "index" %}" class="back">{% trans "Back to ZUKS" %}</a></li>
  <li class="active"><a href="#jump1">{% trans "Newsletter" %}</a></li>
{% endblock "menu" %}

{% block "mobile_menu" %}
  <li>
    <a href="{% url "index" %}" data-toggle="collapse" data-target=".navbar-responsive-collapse" class="back">
        {% trans "Back to ZUKS" %}
    </a>
  </li>
  <li class="active">
    <a href="#" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      {% trans "Newsletter" %}
    </a>
  </li>
{% endblock "mobile_menu" %}

{% block "content" %}
    <div class="section type-3">
      <div class="container">
          {% if status == 'expired' %}
            <h2>{% trans "Link expired" %}</h2>
            <p>
                {% blocktrans %}
                    Your confirmation link is expired.
                    Heads up, subscribe again:
                {% endblocktrans %}
                {% include 'core/subscribe_form.html' %}
            </p>
          {% else %}
            <h1>{% trans "Welcome at ZUKS" %},</h1>
            <h2>{% trans "you successfully subscribed to our newsletter." %}</h2>
            <p>
                {% blocktrans %}
                    We will inform you, when there is something to report about
                    the project, so you stay up to date with our progress.
                {% endblocktrans %}
            </p>
            <p>
                {% blocktrans %}
                    We also post updates on our social media channels regularly.
                    Check them out to get the latest news and discuss with
                    other supporters.
                {% endblocktrans %}
            </p>
          {% endif %}

          {% include 'core/stay_tuned.html' %}
      </div>
  </div>
{% endblock "content" %}

templates/core/contact_form.html
{% load widget_tweaks %}
{% load i18n %}

<form id="contactform" role="form" method="post" action="{% url "send_contactmail" %}">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    <div class="form-group">
        <div class="row">
            <div class="col-lg-6">
              {% trans "Name" as name_placeholder %}
              {% with "placeholder:"|add:name_placeholder|add:" *" as name_placeholder %}
                {{ form.name | add_class:"form-control" | attr:name_placeholder }}
              {% endwith %}
              {{ form.name.errors }}
              <br class="gap-15" />
            </div>
            <div class="col-lg-6">
              {% trans "Email address" as email_placeholder %}
              {% with "placeholder:"|add:email_placeholder|add:" *" as email_placeholder %}
                {{ form.sender | add_class:"form-control" | attr:email_placeholder }}
              {% endwith %}
              {{ form.sender.errors }}
            </div>
        </div>
    </div>
    <div class="form-group">
      {% trans "Subject" as subject_placholder %}
      {% with "placeholder:"|add:subject_placholder|add:" *" as subject_placholder %}
        {{ form.sendersubject | add_class:"form-control" | attr:subject_placholder }}
      {% endwith %}
      {{ form.sendersubject.errors }}
    </div>
    <div class="form-group">
      {% trans "Your text" as text_placholder %}
      {% with "placeholder:"|add:text_placholder|add:" *" as text_placholder %}
        {{ form.content | add_class:"form-control" | attr:text_placholder | attr:"rows:8" }}
      {% endwith %}
      {{ form.content.errors }}
    </div>

    {% if success %}
      <div class="success">
          {% trans "Your message was successfully sent. We will contact you soon." %}
      </div>
    {% endif %}

    <input type="submit" name="submit" id="button-send" class="btn btn-block btn-success" value="{% trans "Send" %}" />
</form>

templates/core/faq.html
{% extends "core/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block "metadata" %}
    <meta name="description" content="FAQ">
    <meta name="keywords" content="FAQ Fragen Antworten Konzept">
{% endblock "metadata" %}

{% block "menu" %}
  <li><a href="{% url "index" %}" class="back">ZUKS</a></li>
  <li class="active"><a href="#faq">FAQ</a></li>
{% endblock "menu" %}

{% block "mobile_menu" %}
  <li>
      <a href="{% url "index" %}" class="back" data-toggle="collapse" data-target=".navbar-responsive-collapse">ZUKS</a>
  </li>
  <li class="active">
      <a href="#faq" data-toggle="collapse" data-target=".navbar-responsive-collapse">FAQ</a>
  </li>
{% endblock "mobile_menu" %}

{% block "content" %}
    <div class="section type-2 faq" id="faq">
        <div class="container">
            <h1>Fragen und Antworten</h1>

            {% for question in questions %}
              {% with question_path|add:question.slug|add:'.html' as template %}
                {% include template %}
              {% endwith %}
            {% endfor %}
        </div>
    </div>

    <div class="section type-1 question" id="question">
      <div class="container">
        <h4 class="headline">{% trans "Ask ZUKS" %}</h4>
        <h2>{% trans "Any questions left? Please tell us!" %}</h2>
        <div class="row">
          <div class="col-lg-7">
              {% include 'core/faq_form.html' %}
          </div>
          <div class="col-lg-5">
              <img src="{% static "img/logo/logo-bild-weiss@320.png" %}" alt="ZUKS Logo Bildmarke" class="content-icon-160" />
          </div>
        </div>
      </div>
    </div>

{% include "core/footer.html" %}

{% endblock "content" %}

templates/core/faq_form.html
{% load widget_tweaks %}
{% load i18n %}

<form id="faqform" role="form" method="post" action="{% url "faq_submit" %}">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    <div class="form-group">
      {% trans "Your question" as text_placholder %}
      {% with "placeholder:"|add:text_placholder|add:" *" as text_placholder %}
        {{ form.text | add_class:"form-control" | attr:text_placholder }}
      {% endwith %}
      {{ form.text.errors }}
    </div>
    
    <div class="form-group">
        <div class="row">
            <div class="col-lg-4">
              {% trans "Name (Pseudonym)" as author_placholder %}
              {% with "placeholder:"|add:author_placholder as author_placholder %}
                {{ form.author | add_class:"form-control" | attr:author_placholder }}
              {% endwith %}
              {{ form.author.errors }}
            </div>
            <div class="col-lg-4">
              {% trans "Twitter name" as twitter_placeholder %}
              {% with "placeholder:"|add:twitter_placeholder as twitter_placeholder %}
                {{ form.twitter_handle | add_class:"form-control" | attr:twitter_placeholder }}
              {% endwith %}
              {{ form.twitter_handle.errors }}
            </div>
            <div class="col-lg-4">
              {% trans "Email address" as email_placeholder %}
              {% with "placeholder:"|add:email_placeholder as email_placeholder %}
                {{ form.email | add_class:"form-control" | attr:email_placeholder }}
              {% endwith %}
              {{ form.email.errors }}
            </div>
        </div>
    </div>
    
    {% if success %}
      <div class="success">
          {% trans "Your question was successfully saved. We will check it soon and integrate it into this FAQ section." %}
      </div>
    {% endif %}

    <input type="submit" name="submit" id="button-send" class="btn btn-block btn-success" value="{% trans "Send" %}" />
</form>

templates/core/google_verification.html
google-site-verification: google2ba41cbba49d5958.html

templates/core/newsletter_backend.html
{% extends "core/base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% load i18n %}

{% block "metadata" %}
    <meta name="description" content="{% trans "Admin Interface to send newsletters" %}">
{% endblock "metadata" %}

{% block "menu" %}
  <li><a href="{% url "admin:index" %}" class="back">{% trans "Administration" %}</a></li>
  <li class="active"><a href="#mail">{% trans "Newsletter" %}</a></li>
{% endblock "menu" %}

{% block "mobile_menu" %}
  <li>
      <a href="{% url "admin:index" %}" class="back" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          {% trans "Administration" %}
      </a>
  </li>
  <li class="active">
      <a href="#mail" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          {% trans "Newsletter" %}
      </a>
  </li>
{% endblock "mobile_menu" %}

{% block "content" %}
    <div class="section type-2" style="padding-top: 100px">
        <div class="container">
            <div>
                <div class="row">
                    <div class="col-lg-5 vertMargin">
                        <h2>
                            {% trans "Editor" %}
                            <a href="http://support.mashery.com/docs/read/customizing_your_portal/Markdown_Cheat_Sheet" class="btn btn-info btn-xs" target="_blank" >{% trans "Markdown help" %}</a>
                        </h2>
                        <form action="{% url 'admin:core_newsletter_add' %}" id="newsletter_form" method="POST" accept-charset="utf-8" class="vertMargin">
                            {% csrf_token %}
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            <div class="form-group">
                                {% trans "Subject" as subject_placeholder %}
                                {% with "placeholder:"|add:subject_placeholder|add:" *" as subject_placeholder %}
                                    {{ form.subject | add_class:"form-control" | attr:subject_placeholder }}
                                {% endwith %}
                                {{ form.subject.errors }}
                            </div>
                            <div class="form-group">
                                {% trans "Markdown Text" as subject_content %}
                                {% with "placeholder:"|add:subject_content|add:" *" as subject_content %}
                                    {{ form.content | add_class:"form-control" | attr:subject_content | attr:"rows:20" | attr:"cols:50" }}
                                {% endwith %}
                                {{ form.content.errors }}
                            </div>

                        </form>
                        <div><button id="send" class="btn btn-primary btn-block">{% trans "Send" %}</button></div>
                    </div>
                    <div class="col-lg-7" >
                       <h2>
                           {% trans "Preview" %}
                           <button class="btn btn-primary btn-xs" id="update_preview">{% trans "Update" %}</button>
                       </h2>
                       <div id="render" class="vertMargin"></div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock "content" %}

{% block "scripts" %}
    <script type="text/javascript" charset="utf-8">
        $("#render").load("{% url 'admin:newsletter-template' %}");

        var should_request = true;
        var updateContent = function() {
            if (should_request) {
                // Timeout to prevent flooding the server
                should_request = false;
                setTimeout(function() {
                    should_request = true;
                }, 500);

                $("#render").load("{% url 'admin:newsletter-template' %}",
                    $('#newsletter_form').serializeArray()
                );
            }
        };

        $('#update_preview').click(updateContent);
        $('#id_content').on('change keyup paste', updateContent);

        $("#send").on('click', function() {
            if (confirm("Nachricht an alle Abonenten versenden?")) {
                $('#newsletter_form').submit();
            }
        });
    </script>
{% endblock %}